import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";

export const metadata = {
  title: "AI FOR AE",
  description: "Generated by XiaoYan app",
};

// headers

export default function RootLayout({ children }: { children: React.ReactNode }) {


  return (
    <html lang="zh" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <main className="flex-grow mt-[72px]">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
